blog_blog:
    resource: "@BlogBlogBundle/Resources/config/routing.yml"
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
blog_blog_blog:
    resource: "@BlogBlogBundle/Resources/config/routing/blog.yml"
    prefix:   /blog